apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation-api
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: validation-api
  template:
    metadata:
      labels:
        app: validation-api
    spec:
      containers:
      - name: validation-api
        image: 123456-dkr.ecr.us-east-1.amazonaws.com/one-technopedia/validation-api:latest
---
apiVersion: v1
kind: Service
metadata:
  name: validation-api
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080

